
openapi: 3.1.0
info:
  title: שליחת סיכום שיחה
  version: 1.2.0
  description: >
    שולח מייל עם סיכום שיחה + קובץ מצורף (אם קיים) לכתובת service@sbcloud.co.il ו־office@sbcloud.co.il.

servers:
  - url: https://smtp-email-sender.onrender.com

paths:
  /send-summary-email:
    post:
      operationId: sendSummaryEmail
      summary: שלח סיכום שיחה
      description: >
        שולח מייל עם פרטי לקוח, סיכום שיחה, וקובץ מצורף (אם נדרש).
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - clientName
                - summary
              properties:
                clientName:
                  type: string
                  description: שם הלקוח
                phone:
                  type: string
                  description: טלפון
                summary:
                  type: string
                  description: סיכום השיחה
                attachment:
                  type: string
                  format: binary
                  description: קובץ מצורף (אופציונלי – תמונה או מסמך)
      responses:
        '200':
          description: המייל נשלח בהצלחה
        '400':
          description: שדות חסרים
        '500':
          description: שגיאה בשליחה
