openapi: 3.1.0
info:
  title: זיהוי ושליחת סיכום שיחה
  version: 1.2.1
  description: >
    מזהה לקוחות לפי שם, חניון או טלפון מקובץ לקוחות (clients.json),
    ושולח סיכום שיחה במייל כולל קובץ מצורף (אם יש).

servers:
  - url: https://smtp-email-sender.onrender.com

paths:
  /identify-client:
    post:
      operationId: identifyClient
      summary: זיהוי לקוח מקובץ
      description: מאתר לקוח לפי שם, חניון או טלפון מתוך קובץ JSON
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientName:
                  type: string
                  description: שם הלקוח
                parkingName:
                  type: string
                  description: שם החניון
                phone:
                  type: string
                  description: טלפון
      responses:
        '200':
          description: לקוח נמצא
        '404':
          description: לקוח לא נמצא
        '500':
          description: שגיאת שרת

  /download-clients:
    get:
      operationId: downloadClients
      summary: הורדת קובץ לקוחות
      description: מחזיר את קובץ clients.json המלא
      responses:
        '200':
          description: קובץ הלקוחות הורד בהצלחה
        '500':
          description: שגיאה בהורדה

  /add-client:
    post:
      operationId: addClient
      summary: הוספת לקוח חדש
      description: מוסיף לקוח לקובץ הלקוחות
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - שם הלקוח
                - שם החניון
                - טלפון
              properties:
                שם הלקוח:
                  type: string
                שם החניון:
                  type: string
                טלפון:
                  type: string
                דואר אלקטרוני:
                  type: string
                כתובת הלקוח:
                  type: string
                קוד קו:
                  type: string
                IP:
                  type: string
                שם החניון בפריורטי:
                  type: string
      responses:
        '201':
          description: לקוח נוסף בהצלחה
        '400':
          description: שדות חסרים
        '500':
          description: שגיאה בשמירה

  /send-summary-email:
    post:
      operationId: sendSummaryEmail
      summary: שליחת סיכום שיחה
      description: >
        שולח מייל עם פרטי לקוח, סיכום שיחה וקובץ מצורף (אם צורף)
        לכתובות service@sbcloud.co.il ו־office@sbcloud.co.il.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - clientName
                - phone
                - summary
              properties:
                clientName:
                  type: string
                  description: שם הלקוח
                phone:
                  type: string
                  description: טלפון
                summary:
                  type: string
                  description: סיכום השיחה
                attachment:
                  type: string
                  format: binary
                  description: קובץ מצורף (תמונה או מסמך, אופציונלי)
      responses:
        '200':
          description: המייל נשלח בהצלחה
        '400':
          description: שדות חסרים
        '500':
          description: שגיאה בשליחה
