openapi: 3.1.0
info:
  title: שליחת סיכום שיחה
  version: 1.0.6
  description: >
    פעולה זו שולחת סיכום שיחה במייל לכתובות הקבועות:
    Service@sbcloud.co.il ו־Office@sbcloud.co.il.

servers:
  - url: https://smtp-email-sender.onrender.com

paths:
  /send-summary-email:
    post:
      operationId: sendSummaryEmail
      summary: שלח סיכום שיחה
      description: שולח מייל עם פרטי הלקוח וסיכום השיחה.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - clientName
                - summary
              properties:
                clientName:
                  type: string
                  description: שם הלקוח
                phone:
                  type: string
                  description: טלפון (לא חובה)
                summary:
                  type: string
                  description: סיכום השיחה או ההזמנה
      responses:
        '200':
          description: Email sent successfully
        '400':
          description: Missing required fields
        '500':
          description: Failed to send email
