openapi: 3.1.0
info:
  title: זיהוי ושליחת סיכום שיחה
  version: 1.1.0
  description: >
    מזהה לקוחות לפי שם, חניון או טלפון מקובץ לקוחות,
    ושולח סיכום שיחה למשרד במייל.

servers:
  - url: https://smtp-email-sender.onrender.com

paths:
  /identify-client:
    post:
      operationId: identifyClient
      summary: זיהוי לקוח מקובץ
      description: מאתר לקוח לפי שם, חניון או טלפון מקובץ JSON
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientName:
                  type: string
                  description: שם הלקוח
                parkingName:
                  type: string
                  description: שם החניון
                phone:
                  type: string
                  description: טלפון
      responses:
        '200':
          description: לקוח נמצא
        '404':
          description: לקוח לא נמצא
        '500':
          description: שגיאה בשרת
  /download-clients:
    get:
      operationId: downloadClients
      summary: הורד את קובץ הלקוחות
      description: מוריד את הקובץ clients.json עם כל הלקוחות
      responses:
        '200':
          description: קובץ הורד בהצלחה
        '500':
          description: שגיאה בהורדה
  /add-client:
    post:
      operationId: addClient
      summary: הוסף לקוח חדש
      description: שומר לקוח חדש לקובץ לקוחות
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - שם הלקוח
                - שם החניון
                - טלפון
              properties:
                שם הלקוח:
                  type: string
                שם החניון:
                  type: string
                טלפון:
                  type: string
                דואר אלקטרוני:
                  type: string
                כתובת הלקוח:
                  type: string
                קוד קו:
                  type: string
                IP:
                  type: string
                שם החניון בפריורטי:
                  type: string
      responses:
        '201':
          description: לקוח נוסף בהצלחה
        '400':
          description: שדות חסרים
        '500':
          description: שגיאה בשמירה

  /send-summary-email:
    post:
      operationId: sendSummaryEmail
      summary: שלח סיכום שיחה
      description: >
        שולח מייל ל־Service@sbcloud.co.il ו־Office@sbcloud.co.il
        עם פרטי הלקוח וסיכום השיחה.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - clientName
                - summary
              properties:
                clientName:
                  type: string
                  description: שם הלקוח
                phone:
                  type: string
                  description: טלפון
                summary:
                  type: string
                  description: סיכום השיחה
      responses:
        '200':
          description: המייל נשלח בהצלחה
        '400':
          description: שדות חסרים
        '500':
          description: שגיאה בשליחה
